### ISSUE TITLE
Logging in shouldn't reload the page

### ISSUE THREAD

**Issue by jhass** [diaspora/jsxc#61]
Title says it all. Mid- to long-term goal but I think it's quickly annoying, especially if you scrolled down the stream for a bit.

**Comment by Flaburgan** [comment]
I was wondering, why don't we put the chat in an iframe? Login / relogin in the chat reload the page, reloading the page or navigating reload the chat... This looks annoying. How does Facebook and Jappix-Mini deal with those problems?

**Comment by Zauberstuhl** [comment]
jappix mini checks on the initialization whether all required parameters are available and then tries to login automatically. jsxc needs a submit event.

In my opinion a iframe is just another workaround. no solution ;)

I have no idea how much work it is to modify jsxc for auto-login, but since we already have a submit-event (on diaspora-login) we could use that, no?!

**Comment by Zauberstuhl** [comment]
looks like a ajax solution is planned for v1.1 (sualko/jsxc#98). That would be my favorite solution!
