### ISSUE TITLE
Ajax connection makes page freeze for 2-3 seconds

### ISSUE THREAD

**Issue by AugierLe42e** [diaspora/jsxc#88]
I'm opening a seperated issue on this because it's more annoying than I first thought. It's really a big problem. JSXC seem to consume more resources now than before. :/

**Comment by Zauberstuhl** [comment]
Can someone confirm that? I have no problems on my Thinkpad Edge 11

**Comment by AugierLe42e** [comment]
I may come from the server though, the JS script freezes until the server answers. As sechat.org is smaller than diaspora-fr.org. So it may answer more quickly.

**Comment by AugierLe42e** [comment]
I've uploaded you a video [here](http://www.c-henry.fr/XMPPlogin.mp4) so you can see how it's like. On the video, the page freezes for about 3 seconds but it's sometimes 4 or 6.

**Comment by Flaburgan** [comment]
@Zauberstuhl you have an account on d-fr right? You can use this invitation link if you need: https://diaspora-fr.org/i/d24d8737f3a9

**Comment by Zauberstuhl** [comment]
Nope I have also no problems with my diaspora-fr account. how many contacts do you have in the chat? If you add all your contacts (1k+) at once I am pretty sure your browser needs some time rendering it (plus the double contact bug).

**Comment by Flaburgan** [comment]
something like ~200 in my 3 aspects where the chat is activated.

**Comment by AugierLe42e** [comment]
I have ~50 contacts which I don't think this is a big amount. That's why I'm concerned on this. It happens on pretty much each page loading, this is a big ergonomic issue to me.

**Comment by Flaburgan** [comment]
I just deactivated temporary the chat on d-fr and I confirm that the page is not freezing anymore, even if I still find it pretty slown to load. Damn...

**Comment by AugierLe42e** [comment]
It's only on connection. We have to find a way to lighten the connection function.

**Comment by Anime-Machina** [comment]
@jhass his reference is valid, I had this problem in the past as well. Clearing the pod its cache and your own browser temporary solves it.

@Zauberstuhl this issue is true my hardware specs:
- Debian 8 (Jessie/Testing)
- Asus Rampage Extreme IV
- Intel i7 920 @ 4.133 GHz
- 12GB DDR 3 Corsair Vengeance (I believe)
- Saphire R9 280 Dual Vapor X

My issue's:
Whole browser turns slow when it is loaded for longer period of times. It fills my RAM up to 6 to 8 GB of memory and eventually FireFox crashes. Crashes happens when having FireFox loaded for extensive amount of time and mostly in combination of HTML5 Web Players for example at crunchyroll.com
